# Generated by Django 3.1.14 on 2022-04-10 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_lista_compras'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
