# Generated by Django 3.1.14 on 2022-04-10 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='concluido',
            field=models.BooleanField(default=False, verbose_name='Concluído'),
        ),
    ]
